# Site settings
title: Bithagoras
email: berkozbalci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Ramblings on math, programming and music.
permalink: /blog/:title
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bozbalci
github_username:  bozbalci

# Build settings
markdown: kramdown
