# Site settings
title: negativland
email: berkozbalci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   computer science. mathematics. avant-garde.
permalink: /:title
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bozbalci
github_username:  bozbalci

# Build settings
markdown: kramdown
